name: 'AI PR review'
description: 'Github action to review PRs using OpenAI'
author: 'mahima-manik'

branding:
  icon: 'check-circle'
  color: 'green'

# Expected inputs for the action
inputs:
  openai-key:
    description: 'OpenAI API key'
    required: true
  github-token:
    description: 'Github token'
    required: true

runs:
  using: node20
  main: dist/index.js
