name: 'AI PR review'
description: 'AI PR review'
author: 'mahima-manik'

# Define your inputs here.
inputs:
  openai-key:
    description: 'OpenAI API key'
    required: true
  github-token:
    description: 'Github token'
    required: true
  files-to-ignore:
    description: 'Files to ignore'
    required: false
    default: '**.md,dist/**,package-lock.json'

# Define your outputs here.
outputs:
  comments:
  description: 'Comments made by AI on PR'

runs:
  using: node20
  main: dist/index.js
