name: 'AI PR review'
description: 'Github action to review PRs using OpenAI'
author: 'mahima-manik'

branding:
  icon: 'check-circle'
  color: 'green'

# Expected inputs for the action
inputs:
  openai-key:
    description: 'OpenAI API key'
    required: true
  github-token:
    description: 'Github token'
    required: true
  gpt-model:
    description: 'Model to use for review. If not provided, defaults to gpt-3.5-turbo.'
    required: false
    default: 'gpt-3.5-turbo'

runs:
  using: node20
  main: dist/index.js
