name: 'AI PR review'
description: 'AI PR review'
author: 'mahima-manik'

# Expected inputs for the action
inputs:
  openai-key:
    description: 'OpenAI API key'
    required: true
  github-token:
    description: 'Github token'
    required: true

runs:
  using: node20
  main: dist/index.js
