name: AI PR review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  packages: read

jobs:
  peer-review:
    runs-on: ubuntu-latest
    name: AI Peer review
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: AI Peer review
        id: ai-peer-review
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-key: ${{ secrets.OPENAI_KEY }}
          gpt-model: gpt-4
